# Generated by Django 4.2.6 on 2023-10-09 04:46
import json

from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


def convert_to_streamfield(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    for page in BlogPage.objects.all():
        page.body = json.dumps(
            [{"type": "rich_text", "value": page.body}], cls=DjangoJSONEncoder
        )
        page.save()


def convert_to_richtext(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    for page in BlogPage.objects.all():
        if page.body:
            stream = json.loads(page.body)
            page.body = "".join(
                [child["value"]
                    for child in stream if child["type"] == "rich_text"]
            )
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blogtagindexpage"),
    ]

    operations = [
        migrations.RunPython(convert_to_streamfield, convert_to_richtext),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
