# Generated by Django 4.2.6 on 2023-10-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="body",
            new_name="intro",
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro_title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
