# Generated by Django 4.2.6 on 2023-10-09 04:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("blog", "0006_alter_blogpage_body"),
        ("home", "0004_rename_body_homepage_intro_homepage_intro_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeToolIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PracticeToolPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("short_description", wagtail.fields.RichTextField(blank=True)),
                ("long_description", wagtail.fields.RichTextField(blank=True)),
                ("location", models.URLField(blank=True)),
                ("tags", models.ManyToManyField(blank=True, to="blog.blogpagetag")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
