# Generated by Django 4.2.6 on 2023-10-11 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_practicetooltagindexpage_practicetoolpage_featured_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practicetoolpage",
            name="tags",
        ),
        migrations.DeleteModel(
            name="PracticeToolTag",
        ),
    ]
